# Generated by Django 4.2.5 on 2023-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
    ]
