# Generated by Django 4.2.5 on 2023-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_publication_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publication_sign',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.DateField(auto_now_add=True, verbose_name='дата'),
        ),
    ]
